"""Add users table

Revision ID: 1029d4344cd4
Revises: e6cfb309a4e7
Create Date: 2025-09-17 22:47:26.180401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1029d4344cd4'
down_revision: Union[str, Sequence[str], None] = 'e6cfb309a4e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history_user', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('history_user', sa.Column('interaction', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_history_user_user_token'), table_name='history_user')
    op.create_foreign_key(None, 'history_user', 'teacher_info', ['user_id'], ['id'])
    op.drop_column('history_user', 'created_at')
    op.drop_column('history_user', 'question')
    op.drop_column('history_user', 'response')
    op.drop_column('history_user', 'user_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history_user', sa.Column('user_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('history_user', sa.Column('response', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('history_user', sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('history_user', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'history_user', type_='foreignkey')
    op.create_index(op.f('ix_history_user_user_token'), 'history_user', ['user_token'], unique=False)
    op.drop_column('history_user', 'interaction')
    op.drop_column('history_user', 'user_id')
    # ### end Alembic commands ###
