"""create user table

Revision ID: b8d79478ab17
Revises: 99032e80daf4
Create Date: 2025-09-17 18:02:30.466712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8d79478ab17'
down_revision: Union[str, Sequence[str], None] = '99032e80daf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history_user', sa.Column('user_token', sa.String(), nullable=True))
    op.add_column('history_user', sa.Column('question', sa.Text(), nullable=False))
    op.add_column('history_user', sa.Column('response', sa.Text(), nullable=False))
    op.add_column('history_user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_history_user_id'), 'history_user', ['id'], unique=False)
    op.create_index(op.f('ix_history_user_user_token'), 'history_user', ['user_token'], unique=False)
    op.drop_constraint(op.f('history_user_user_id_fkey'), 'history_user', type_='foreignkey')
    op.drop_column('history_user', 'user_query')
    op.drop_column('history_user', 'user_id')
    op.drop_column('history_user', 'userinfo_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history_user', sa.Column('userinfo_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('history_user', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('history_user', sa.Column('user_query', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('history_user_user_id_fkey'), 'history_user', 'teacher_info', ['user_id'], ['id'])
    op.drop_index(op.f('ix_history_user_user_token'), table_name='history_user')
    op.drop_index(op.f('ix_history_user_id'), table_name='history_user')
    op.drop_column('history_user', 'created_at')
    op.drop_column('history_user', 'response')
    op.drop_column('history_user', 'question')
    op.drop_column('history_user', 'user_token')
    # ### end Alembic commands ###
